runtime: python
env: flex

instance_class: F1

# Flexible Environment scaling settings
automatic_scaling:
  min_num_instances: 1
  max_num_instances: 10

env_variables:
  GOOGLE_APPLICATION_CREDENTIALS: "YOUR_GOOGLE_CREDENTIALS"

handlers:
  - url: /.*
    script: auto